import { Cable, Download, MicOff, Square, Trash2 } from 'lucide-react'
import type { InputState } from '../../types'
import type { RecordingState } from './useRecorder'

type Props={inputState:InputState;devices:MediaDeviceInfo[];deviceId:string;inputLevel:number;inputError:string;recordingState:RecordingState;recordingUrl:string;recordingSeconds:number;recordingMime:string;onSelectInput:(id?:string)=>void;onDisconnect:()=>void;onStart:()=>void;onStop:()=>void;onClear:()=>void}

export function RecorderStudio({inputState,devices,deviceId,inputLevel,inputError,recordingState,recordingUrl,recordingSeconds,recordingMime,onSelectInput,onDisconnect,onStart,onStop,onClear}:Props){
  const listening=inputState==='listening',time=`${String(Math.floor(recordingSeconds/60)).padStart(2,'0')}:${String(recordingSeconds%60).padStart(2,'0')}`
  return <section className="recorder-studio">
    <div className="studio-toolbar"><div><span className={`device-light ${listening?'online':''}`}/><strong>{listening?'输入设备已就绪':'尚未连接输入设备'}</strong><small>{listening?(devices.find((device)=>device.deviceId===deviceId)?.label||'USB 音频输入'):'支持 G5n、USB 声卡和设备麦克风'}</small></div>{listening&&devices.length>1&&<select value={deviceId} onChange={(event)=>onSelectInput(event.target.value)}>{devices.map((device,index)=><option key={device.deviceId} value={device.deviceId}>{device.label||`音频输入 ${index+1}`}</option>)}</select>}<button className="studio-connect" disabled={inputState==='requesting'} onClick={listening?onDisconnect:()=>onSelectInput()}>{listening?<><MicOff size={15}/>断开设备</>:<><Cable size={15}/>{inputState==='requesting'?'连接中…':'连接设备'}</>}</button></div>
    <div className={`studio-deck ${recordingState}`}><div className="studio-display"><span>{recordingState==='recording'?'RECORDING':recordingState==='ready'?'TAKE READY':'READY'}</span><time>{time.slice(0,2)}<i>:</i>{time.slice(3)}</time><small>{recordingState==='recording'?'正在录制设备输入原声':listening?'按下录音键开始':'请先连接输入设备'}</small></div><div className="studio-wave" aria-hidden="true">{Array.from({length:44},(_,index)=><i key={index} style={{height:`${listening?Math.max(3,inputLevel*54*(.45+.55*Math.abs(Math.sin(index*.72)))):3}px`}}/>)}</div><div className="studio-meter"><span>L</span><div><i style={{width:`${inputLevel*100}%`}}/></div><b>{inputLevel>.8?'PEAK':Math.round(inputLevel*100)}</b></div><div className="transport-controls">{recordingState!=='recording'?<button className="main-record" disabled={!listening} onClick={onStart}><span/><strong>{recordingState==='ready'?'重新录制':'开始录音'}</strong></button>:<button className="main-stop" onClick={onStop}><Square size={19}/><strong>停止录音</strong></button>}</div></div>
    {recordingState==='ready'&&recordingUrl&&<section className="take-panel"><div><span>当前录音</span><strong>吉他录音 · {time}</strong></div><audio src={recordingUrl} controls/><a href={recordingUrl} download={`guitar-${new Date().toISOString().slice(0,19).replace(/:/g,'-')}.${recordingMime.includes('ogg')?'ogg':recordingMime.includes('mp4')?'m4a':'webm'}`}><Download size={15}/> 下载录音</a><button onClick={onClear}><Trash2 size={15}/> 删除</button></section>}
    {inputState==='error'&&<p className="studio-error">{inputError}</p>}<p className="recorder-tip">录音只保存在当前浏览器中。下载前请不要刷新页面；使用 G5n 时将录制其 USB 输入提供的声音。</p>
  </section>
}
