import { BarChart3, Brain, Headphones, MapPin, Play, RotateCcw } from 'lucide-react'
import type { PracticeProfile, StageResult } from '../../lib/practiceProfile'

type Props={profile:PracticeProfile;result:StageResult[]|null;onStart:()=>void;onContinue:()=>void}
const LABELS:Record<string,string>={locate:'音名定位',identify:'反向识别',stringLocate:'指定弦定位',octave:'八度关系',earLocate:'听音定位'}

export function AssessmentPage({profile,result,onStart,onContinue}:Props){
  if(result){const sorted=[...result].sort((a,b)=>a.accuracy-b.accuracy),accuracy=Math.round(result.reduce((sum,item)=>sum+item.correct,0)/Math.max(1,result.reduce((sum,item)=>sum+item.attempts,0))*100);return <section className="assessment-page result"><div className="assessment-result-head"><BarChart3 size={28}/><span>诊断完成</span><h2>你的当前指板能力：{accuracy}%</h2><p>课程已根据本次结果和具体指板位置的反应速度重新安排。</p></div><div className="assessment-results">{sorted.map((item)=><div key={item.type}><strong>{item.accuracy}%</strong><span>{LABELS[item.type]||item.type}</span><small>{item.correct}/{item.attempts} 正确</small></div>)}</div><div className="assessment-analysis"><strong>主要薄弱项</strong><span>{sorted.slice(0,2).map((item)=>LABELS[item.type]||item.type).join('、')}</span><p>这些内容会在下一套每日 10 分钟中获得更多练习时间。以后每次完成每日训练，课程还会继续调整。</p></div><button className="assessment-primary" onClick={onContinue}>查看我的 10 分钟课程</button></section>}
  return <section className="assessment-page"><div className="assessment-intro"><span>INITIAL SKILL CHECK</span><h2>{profile.assessmentCompleted?'重新进行能力诊断':'先用 5 分钟了解你的当前水平'}</h2><p>考试使用现有训练规则，每项一分钟。不会因为答错而中断，尽量快速、自然地作答。</p></div><div className="assessment-features"><div><MapPin/><strong>视觉定位</strong><span>音名、位置与指定琴弦</span></div><div><Brain/><strong>关系理解</strong><span>八度形状与空间记忆</span></div><div><Headphones/><strong>听觉映射</strong><span>听到声音后找到实际位置</span></div></div><div className="assessment-notice"><RotateCcw size={17}/><span>清除本地缓存后会重新进入本次诊断，因为原有学习档案也会被删除。</span></div><button className="assessment-primary" onClick={onStart}><Play size={17}/> 开始 5 分钟诊断</button></section>
}
